apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default-spot-arm64
spec:                  
  amiSelectorTerms:                           
    - alias: bottlerocket@latest 
  role: karpenter-node-role
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "eks-karpenter-demo"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "eks-karpenter-demo"
