apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: spot-x86-armd64
spec:
  amiSelectorTerms:
    - alias: al2023@v20250627
  role: karpenter-node-role
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "eks-karpenter-demo"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "eks-karpenter-demo"
