apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: spot-arm64
spec:
  template:
    spec:
      expireAfter: 5m
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default-spot-arm64
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]
        - key: kubernetes.io/arch
          operator: In
          values: ["arm64"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["t", "m", "c"]       
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["5"]   
  limits:
    cpu: "10"
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s
    expireAfter: 10s
